### PR TITLE
Fix mounts leak

### LINKED ISSUE #7: Fix mount leak
Default mounts will leak when spawn fails.

### PR DESCRIPTION
**Pull request by mflagey**
This PR is to fix mounts leak when spawn command fails. 

- [x] Fix leak
- [x] Add unit test

Test case: Try to run container with empty rootfs. Run should fail and /proc/mounts of host system should not be modified before and after run.

close #7

### CODE REVIEW

File: container/src/lib.rs [hunk 1]
```diff
@@ -86,20 +87,23 @@ impl Container {
...
+                Err(_) => {
+                    let _ = &self.mounts.cleanup(self.rootfs.clone())?;
+                    exit(2);
+                }
+            };
+            child.wait().map_err(Error::ContainerWaitCommand)?.code()
         };
 
         let _ = &self.mounts.cleanup(self.rootfs.clone())?;
-
```
Comment (sameo) [inline container/src/lib.rs]: Unneeded change, please remove it.

File: container/src/mounts.rs [hunk 2]
```diff
@@ -42,6 +42,7 @@ impl Mounts {
             path.push(&mount.source);
 
             if let Some(code) = Command::new("umount")
+                .arg("-l")
```
Comment (sameo) [inline container/src/mounts.rs]: Why do we need a lazy unmount here?

File: container/src/lib.rs [hunk 3]
```diff
@@ -86,20 +87,23 @@ impl Container {
...
                 .spawn()
-                .map_err(Error::ContainerSpawnCommand)?
-                .wait()
-                .map_err(Error::ContainerWaitCommand)?
-                .code()
+            {
+                Ok(child) => child,
+                Err(_) => {
+                    let _ = &self.mounts.cleanup(self.rootfs.clone())?;
+                    exit(2);
```
Comment (sameo) [inline container/src/lib.rs]: You should not `exit`here but propagate the cleanup error by just `return self.mounts.cleanup(self.rootfs.clone());`

File: container/src/lib.rs [hunk 4]
```diff
@@ -86,20 +87,23 @@ impl Container {
...
+                }
+            };
+            child.wait().map_err(Error::ContainerWaitCommand)?.code()
         };
 
         let _ = &self.mounts.cleanup(self.rootfs.clone())?;
```
Comment (sameo) [inline container/src/lib.rs]: I believe we should be able to just do `self.mounts.cleanup(self.rootfs.clone())?;`here.

**Review by sameo — COMMENTED** [review]
Thanks for the PR @NelopsisCode.

For unit testing, it's not going to be completely trivial. You could have a container runtime spec fixture file, and then use it with an empty, temporary rootfs. Before calling into `run`, you could read `/proc/mounts`on the host system and store that read in a buffer.
Then you call `run`, which should fail because of your empty rootfs. Then you read again `/proc/mounts`and it should be identical as the one you read right before the test.

It is slightly racy, but probably good enough as a unit test (Especially if we're running this in a github actions, which are containeriyed themselves).

File: container/src/mounts.rs (hunk 2 above)
Comment (mflagey) [reply container/src/mounts.rs]: I added this argument prevent the cleanup from errors due to busy mounts.

File: container/src/lib.rs (hunk 3 above)
Comment (mflagey) [reply container/src/lib.rs]: Ok, I changed that but I have a question. 
When I tried to write `self.mounts.cleanup(self.rootfs.clone())` instead of `return self.mounts.cleanup(self.rootfs.clone())`, I got an error `expected struct unshare::Child, found enum std::result::Result`.
Is it not the same to write `lastline` without semicolon and to write `return lastline;` ?

Comment (sameo) [reply container/src/lib.rs]: >  Is it not the same to write `lastline` without semicolon and to write `return lastline;` ?

The former is what the current scope (what's between `{}`) while the latter is a return from the root function scope (return from function).

In your example, you get an error because the scope is the `match`, and you bind a variable to the return value of the scope. If on the `Ok(child)` path your scope returns a `unshare::Child`, the `Err()` should also return the same type. If you call `return` from the `Err()` branch, then what you should return is of the same type as the function/method return value.
I hope it makes sense.

File: container/Cargo.toml [hunk 5]
```diff
@@ -9,4 +9,5 @@ lazy_static = "1.4.0"
 oci-spec = "0.5.3"
 unshare = { git = "https://github.com/virt-do/unshare", branch = "main" }
 serde = { version = "1.0", features = ["derive"] }
-serde_json = "1.0"
\ No newline at end of file
+serde_json = "1.0"
+proc-mounts = "0.3.0"
```
Comment (sameo) [inline container/Cargo.toml]: Add this dependency under `[dev-dependencies]` so that we don't pull it when generating the binary, but only for the tests.

File: container/src/mounts.rs (hunk 2 above)
Comment (sameo) [reply container/src/mounts.rs]: It should not fail. Adding `-l` will hide an issue that needs to be fixed.
I'm not saying you should fix said issue in that PR, but you should not hide it so that it can be fixed later on.

**Review by sameo — COMMENTED** [review]
Looks pretty good, thanks @NelopsisCode .

I have a couple of comments that you need to address. And you have to rebase your branch on top of main.

File: container/Cargo.toml (hunk 5 above)
Comment (mflagey) [reply container/Cargo.toml]: Ok, I did it!

File: container/src/lib.rs (hunk 3 above)
Comment (mflagey) [reply container/src/lib.rs]: Yes it's clear, thank you for your response !

**Comment by mflagey** [comment]
Hello @sameo , 
I have a question about unit testing. 
As you can see in checks, my test failed because it needs hack/ctr-bundle folder to run a container. This folder is created by hack/mkbundle.sh
Should I modify GitHub actions to run hack/mkbundle.sh before running unit tests ?

**Comment by sameo** [comment]
> Hello @sameo , I have a question about unit testing. As you can see in checks, my test failed because it needs hack/ctr-bundle folder to run a container. This folder is created by hack/mkbundle.sh Should I modify GitHub actions to run hack/mkbundle.sh before running unit tests ?

Just create a [temp directory](https://docs.rs/tempdir/latest/tempdir/) and copy a spec.json file in there (if needed).

**Comment by mflagey** [comment]
> Just create a [temp directory](https://docs.rs/tempdir/latest/tempdir/) and copy a spec.json file in there (if needed).

Yes but I need to have this spec.json in the container used for unit testing. Should I push a testspec.json in the repository ?

**Comment by sameo** [comment]
> > Just create a [temp directory](https://docs.rs/tempdir/latest/tempdir/) and copy a spec.json file in there (if needed).
> 
> Yes but I need to have this spec.json in the container used for unit testing. Should I push a testspec.json in the repository ?

Yes, you can push a `spec.json` under e.g. a `fixtures` folder.

**Review by sameo — APPROVED** [review]
Nice work @NelopsisCode
